name: Deploy examples to gh-pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare --activate
          pnpm install --frozen-lockfile

      - name: Build example project
        run: pnpm run build

      - name: Deploy example page to gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch --orphan gh-pages
          git add -f ./docs
          git commit -m "chore: update release"
          git push -f origin gh-pages
